test:
 script:
  - flutter pub get
  - flutter test

build:
 script:
  - flutter pub get
  - flutter clean
  - flutter build apk
 artifacts:
    paths:
      - $CI_PROJECT_DIR/build/app/bundle/release/app-release.apk